- MANIFEST.in
- setup.py
> Add schema files to source and binary distribution

- ocpp/v16/call.py
> Fix typo in attribute of call.StartTransactionPayload

- ocpp/v16/enums.py
It solves -> [https://github.com/mobilityhouse/ocpp/issues/18](https://github.com/mobilityhouse/ocpp/issues/18)
> Solved issue #18 -> Mispeling of RemoteStopTransaction

- ocpp/v16/call.py
> Fix attributes of call.StopTransactionPayload

- ocpp/v16/call.py
- ocpp/v16/call_result.py
> Fix several type hints in call and call_result

- ocpp/v16/call.py
- ocpp/v16/call_result.py
> Fix typo in DiagnosticsStatusNotification

- ocpp/v16/call.py
- ocpp/v16/enums.py
> Fix typos in ocpp.v16 classes

- .gitignore
- ocpp/v16/call.py
This PR is a result of the issue opened by @psauer: [https://github.com/mobilityhouse/ocpp/issues/48](https://github.com/mobilityhouse/ocpp/issues/48)
> Fixed ReserveNow payload creation

- README.rst
- docs/source/central_system.rst
- ocpp/messages.py
- ocpp/routing.py
- tests/v20/test_v20_charge_point.py
Thanks a lot for the great documentation @OrangeTux 
I did not have the time to go over everything and those are just small fix of small typos
1. contribution, not super proud of it but... :walking_woman:
> Fix small typos in the documentation

- ocpp/charge_point.py
- tests/v16/test_v16_charge_point.py
> Validate calls before sending

- ocpp/v16/call.py
- ocpp/v16/call_result.py
- ocpp/v20/call.py
- ocpp/v20/call_result.py
> Fix 'Optional' type hints

- examples/v16/central_system.py
- examples/v20/central_system.py
- examples/v201/central_system.py
- examples/v201/charge_point.py
Also fixed subprotocol handling in all examples
fixes #142
> Added Example to OCPP 2.0.1

- README.rst
Enhanced the example by checking the subprotocols supported by the CS
fixes #143
> Updated Readme to include support to OCPP 2.0.1 

- ocpp/v16/call.py
- Add the connector ID as ChangeAvailability.req
field.
- Remove AvailabilityType and use AvailabityStatus
for the `status` field.
Fix: https://github.com/mobilityhouse/ocpp/issues/147
> fix ChangeAvailability.req for ocpp v1.6

- README.rst
- docs/source/central_system.rst
- examples/v16/central_system.py
- examples/v20/central_system.py
- examples/v201/central_system.py
> fix/typo: on_boot_notification

- ocpp/charge_point.py
- ocpp/v201/datatypes.py
- pyproject.toml
- tests/test_charge_point.py
Adding the various datatypes for v2.0.1 as I didn't see them in the repo already.
> Add v2.0.1 data types

- .github/workflows/pull-request.yml
- examples/v16/central_system.py
- examples/v16/charge_point.py
- examples/v20/central_system.py
- examples/v20/charge_point.py
- examples/v201/central_system.py
- examples/v201/charge_point.py
- poetry.lock
- pyproject.toml
fixes:https://github.com/mobilityhouse/ocpp/issues/314
> Drop Python 3.6 support and update jsonschema to 4.4

- ocpp/v201/datatypes.py
fixes #305
@Shadowsith reported the issue but did not propose a pull request.
As I ran into the same issue, I hope it gets fixed soon with this pull request.
Thank you!
> Add missing MeasurandType to SampledValueType

- CHANGELOG.md
> Fix changelog links for 0.10.0

- ocpp/v201/enums.py
- tests/v201/test_v201_enums.py
Adding 3 new connector types from the Errata, and any missing descriptions.
> Add new connector types from errata

- ocpp/v201/enums.py
- tests/v201/test_v201_enums.py
Adding a new datatype from the errata:
> Add passwordString datatype enum

- CHANGELOG.md
- poetry.lock
See https://github.com/mobilityhouse/ocpp/issues/559 for packages updated
Replaces PR's https://github.com/mobilityhouse/ocpp/pull/489, https://github.com/mobilityhouse/ocpp/pull/461, https://github.com/mobilityhouse/ocpp/pull/454, https://github.com/mobilityhouse/ocpp/pull/568
> Update project dependencies as of 22-12-2023

- CHANGELOG.md
- ocpp/charge_point.py
- tests/test_charge_point.py
see issue https://github.com/mobilityhouse/ocpp/issues/591
> Fix camel_to_snake_case for "v2x"

- CHANGELOG.md
- ocpp/v201/enums.py
> Correct naming of members of `v201.enums.AttributeType` 

- CHANGELOG.md
- ocpp/v16/enums.py
See issue https://github.com/mobilityhouse/ocpp/issues/574
> Remove v1.6 deprecated enum variants

- .readthedocs.yaml
- CHANGELOG.md
See issue https://github.com/mobilityhouse/ocpp/issues/515
> Readthedocs_configuration_is_outdated

- .readthedocs.yaml
see issue https://github.com/mobilityhouse/ocpp/issues/515
> Readthedocs_configuration_is_outdated_config_update

- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
- [#573](https://github.com/mobilityhouse/ocpp/issues/573) Introduce Experimental Module For v2.1
- [#547](https://github.com/mobilityhouse/ocpp/pull/547) Feat: Handle recursively serializing a dataclasses as a dictionary Thanks [@MacDue](https://github.com/MacDue)
- [#601](https://github.com/mobilityhouse/ocpp/issues/601) Fix case conversion for soc in non "State of Charge" context
- [#523](https://github.com/mobilityhouse/ocpp/issues/523) The serialisation of soc to SoC should not occur in camel case if it is existing at the beginning of a field
- [#515](https://github.com/mobilityhouse/ocpp/issues/515) Update Readthedocs configuration
- [#602](https://github.com/mobilityhouse/ocpp/issues/602) Correct v2g serialisation/deserialisation
- …
> Bump to 1.0.0-rc.1

- README.rst
This commit fixes the README.rst so that Pypi accepts it.
Fixes: #631
> Fix release to PYPI

- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/documentation_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
Adds issue templates, contributes to https://github.com/mobilityhouse/ocpp/issues/671
> Add issue templates

- README.rst
I just removed my access the project's Github and Pypi.
Thanks for moving this project for forward @mdwcrft , @jainmohit2001  and  @proelke . Good luck!
@mdwcrft I didn't include your last name, since your Github profile doesn't expose that information. 
Let me know if you want to include that.
cc: @Jared-Newell-Mobility
> Finalize hand over to new maintainers.

- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
Docs updates to reflect next release
> docs: prep for 2.0.0-rc.4 release

- poetry.lock
> chore(deps): apply minor and patch updates

- .readthedocs.yaml
- docs/requirements.txt
- Bug fix: Added missing requirements.txt file for sphinx project.
1. [x] Does your submission pass the existing tests?
2. [ ] Are there new tests that cover these additions/changes? 
3. [x] Have you linted your code locally before submission?
> fix: Add requirements for Sphinx documentation build

- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
Bumps versions and changelog for upcoming 2.1.0-rc.1 release
> Bump to v2.1.0-rc.1

- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
Bump version numbers for 2.1.0 release
> release: 2.1.0 version bump
