mobilityhouse/ocpp

- .circleci/config.yml
- requirements.txt
- requirements_dev.txt
- setup.py
Also jsonschema has been updated because the configured version, 2.6.0,
conflicted with the version required by poetry.
Fixes: #3
> Add CircleCI configuration.

- ocpp/v16/charge_point.py
If a call is used in the 'after' handler, it can block the event loop, so it is better to run the coroutine in a task.
> Use create_task when executing the 'after' handler coroutine

- ocpp/v16/call.py
- ocpp/v16/call_result.py
As Rahul Dahiya <rahuldahiya33@gmail.com> mentioned, the data type of DataTransfer was wrong. This PR is to fix that issue.
> Fixed wrong data type in dDataTransfer messages

- .circleci/config.yml
- poetry.lock
Initally Pytest failed to collect the tests and crashed with:
``` python
File "/home/developer/.pyenv/versions/3.8.0/lib/python3.8/importlib/metadata.py", line 379, in find_distributions
found = cls._search_paths(context.pattern, context.path)
AttributeError: 'str' object has no attribute 'pattern'
```
Updating all depedencies fixed it.
> Add Python 3.8 support

- ocpp/charge_point.py
- tests/v16/test_v16_charge_point.py
ocpp.ChargePoint.call() implements flow control as defined in the OCPP
specification. It makes sure that no call can be send after an answer on
the previous request has been received.
A lock is used to implement flow control. If the call `await
self._send(call.json())` crashed it the lock wouldn't be released
which could lead to a deadlock.
Thanks @psauer for reporting.
Fixes: #46
> Fix potential deadlock

- ocpp/charge_point.py
The fix introduced for #46 contained a bug. `ChargePoint.call()`
could fail with:
``` python
try:
await self._send(call.to_json())
response = \
await self._get_specific_response(call.unique_id,
self._response_timeout)
finally:
self._call_lock.release()
>           raise
E           RuntimeError: No active exception to reraise
```
Fixes: #50
> Don't reraise exception in finally block

- ocpp/messages.py
- tests/test_messages.py
The validation of payloads using jsonschemas could fail when the payload
contained a float. This problem is described in this issue:
https://github.com/Julian/jsonschema/issues/247
This commit implements a work around for this issue by changing the
float parser for certain payloads from `float()` to `decimal.Decimal()`.
Fixes: #43
> Fix validation of payloads containing floats

- ocpp/charge_point.py
- ocpp/routing.py
- tests/test_routing.py
- tests/v16/test_v16_charge_point.py
The argument can be used to skip validation of a request and response.
It defaults to `False`, so by default validation is enabled.
The reasoning for this change is that TMH has charge points which use
measurands inside MeterValues messages which are not compliant with the
OCPP 1.6 specification. Therefore the validation of these messages fail.
With this new argument validation of certain messages can be disabled.
Fixes: #54
> Add arg `skip_schema_validation` to @on()

- ocpp/messages.py
- tests/v16/test_v16_charge_point.py
- tests/v20/test_v20_charge_point.py
Several charge point vendors have problems JSON messages with spaces
after a separator. Separators are `,` and `:` in a JSON message.
This commit removes them.
Fixes: #63
> Remove white space after separator

- ocpp/charge_point.py
- ocpp/messages.py
- tests/test_messages.py
Version `0.6.0` forces validation of `Call`s before they are send to the
other end. The validation of `call.SetChargingProfilePayload` fails with
a TypeError. The charging profile contains a value of type
`decimal.Decimal` and this value cannot be serialized to JSON. The
problem can be demonstrated like this:
>>> import decimal
>>> import json
>>> >>> json.dumps(decimal.Decimal(3))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/developer/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/home/developer/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/home/developer/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.p …
> Fix JSON encoding of decimal.Decimal

- ocpp/v16/enums.py
- ocpp/v16/schemas/MeterValues.json
- tests/test_messages.py
- tests/v16/test_enums.py
Updated the MeterValues schema to allow a unit of measure called "Hertz".
This was missing from the original 1.6 spec, but was added as an errata (see the
OCPP 1.6 Errata sheet, v4.0 Release, 2019-10-23, on page 34).
We've seen this unit of measure used in MeterValues messages from a "Viridian"
brand charger (which uses Evnex OCPP firmware), and we were having to work
around it by skipping schema validation of MeterValues messages.
> Added Hertz as a valid unit of measure, added a test

- pyproject.toml
This makes it possible to go from the PyPI page to relevant docs, without having to guess with a search engine :)
> Add repository and documentation links

- ocpp/v20/call.py
The names of the following OCPP 2.0 call payloads where fixed:
* RequestStartTransactionPayload
* RequestStopTransactionPayload
Fixes: #76
> Fix names of 2 OCPP OCPP 2.0 call payloads

- README.rst
- examples/v16/central_system.py
- examples/v16/charge_point.py
- examples/v20/central_system.py
- examples/v20/charge_point.py
In several issues it became clear that users didn't knew how to enable
logging for the package. Therefore I enabled INFO logging in all
examples.
> Enable logging in examples

- ocpp/exceptions.py
Issue description:
Currently, errors in ocpp.exceptions lack a __str__() implementation.
Therefore, the following code doesn't print the error:
```
try:
// Something that raises an exception.
except ocpp.exceptions.OCPPError as e:
logger.warning("Failed to do something: %s", e)
```
Closes #105
> Allow __str__ representation to print exceptions

- ocpp/charge_point.py
Issue: https://github.com/mobilityhouse/ocpp/issues/95
in order to avoid the following warning:
```
/.../lib/python3.8/site-packages/ocpp/charge_point.py:184:
DeprecationWarning: "@coroutine" decorator is deprecated
since Python 3.8, use "async def" instead
response = await asyncio.coroutine(handler)(**snake_case_payload)
```
as the function can be a normal function or a coroutine, the
following check can be used to await the function.
```
response = handler(**snake_case_payload)
if inspect.isawaitable(response):
response = await response
```
> Python 3.8 warnings

- examples/v16/central_system.py
- examples/v16/charge_point.py
- ocpp/v16/enums.py
Subclassing from `enum.Enum` has several benefits:
* type hinting of handlers, Calls and CallResults can be improved
* improves integration with frame works like Django
* enums can be enumerated more easily
Subclassing from `str` gives backwards compatibility. Without it
all calls like `AuthorizationStatus.accepted` had to be replaced with
`AuthorizationStatus.accepted.value()`.
Fixes: #110
> Subclass OCPP 1.6 enums from str and enum.Enum

- ocpp/charge_point.py
- tests/v16/test_v16_charge_point.py
The response of the handler was passed to `asyncio.ensure_future()`
and that resulted in a `TypeError`.
```
Traceback (most recent call last):
File "/home/developer/projects/tmh-ocpp/.env/lib/python3.8/site-packages/websockets/server.py", line 191, in handler
await self.ws_handler(self, path)
File "examples/v16/central_system.py", line 44, in on_connect
await cp.start()
File "/home/developer/projects/tmh-ocpp/.env/lib/python3.8/site-packages/ocpp/charge_point.py", line 126, in start
await self.route_message(message)
File "/home/developer/projects/tmh-ocpp/.env/lib/python3.8/site-packages/ocpp/charge_point.py", line 144, in route_message
await self._handle_call(msg)
File "/home/developer/projects/tmh-ocpp/.env/lib/python3.8/site-packages/ocpp/charge_point.py", line 222, in _handle_call …
```
> Fix execution of async `@after()` handlers.

- .circleci/config.yml
Python 3.9 has been released and Travis
should run the test against this python version.
Signed-off-by: Laysa Uchoa <laysa.uchoa@gmail.com>
> Issue 131: Add support for Python 3.9

- ocpp/charge_point.py
0.7.1 reintroduced a deadlock bug that was already fixed in 0.4.2.
Sending a call in an `@after` handler would cause a deadlock.
Fixes #130
> Fix deadlock in `@after` handler

- .circleci/config.yml
Docker hub is changing it's policy as of November 1 2020. It will start
to rate limit pulls of images for non-paying users. This repo relies on
Docker hub for it's automated tests. In order to avoid to be rated
limited this the CircleCI job should log in to Docker hub before pulling
the Python images.
Fixes: #150
> Log in to Docker hub to prevent being rate limited

- ocpp/v16/enums.py
- ocpp/v201/enums.py
- tests/v16/test_enums.py
The conversion in the ocpp1.6 includes also the old enums to ensure backwards compatibility 
fixes #114
> Converted all camelCase and PascalCase enums to snake_case, except Action enumeration

- ocpp/messages.py
- tests/test_messages.py
Creating a `Draft4Validator` instance from a dict representation of a
JSON schema is pretty expensive. Therefore caching the instances makes
sense.
I've done some micro benchmarks. Below are the results:
As expected benchmarks `test_xxxx_with_validation` show an significant performance improvement. 
`test_meter_values_with_validation` is 1.88 times faster.
`test_boot_notifications_with_validation` is 2.60  times faster.
Fixes: #154
> Optimize validation by caching `Draft4Validator`s

- README.rst
- docs/source/central_system.rst
- ocpp/routing.py
Cover that it can take an async function as well as a sync one, and use that in examples. Using async would be preferred as it allows `await`-ing DB I/O etc. whilst handling a call.
Also make the terms used a bit more consistent - “handler” throughout instead of “hook”, and recommend taking `**kwargs`` to ignore future arguments.
> Improve documentation of on()

- CHANGELOG.md
- ocpp/v201/call.py
The prefix `Request` was missing for the OCPP 2.0.1 call payloads
`RequestStartTransaction` and `RequestStopTransaction`.
Fix: #167
> Fix OCPP 2.0.1 call payloads RequestStartTransactionPayload and RequestStopTransactionPayload

- examples/v16/central_system.py
- examples/v20/central_system.py
- examples/v201/central_system.py
The examples for the central systems contained a bug. This bug could
lead to a `UnboundLocalError` if a client wouldn't send a
`Sec-WebSocket-Protocol` along with the websocket handshake.
```
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
File "/home/developer/projects/tmh-ocpp/.env/lib/python3.8/site-packages/websockets/server.py", line 191, in handler
await self.ws_handler(self, path)
File "examples/v16/central_system.py", line 54, in on_connect
requested_protocols)
UnboundLocalError: local variable 'requested_protocols' referenced before assignment
```
Fixes #178
> Fix `UnboundLocalError` in examples

- ocpp/charge_point.py
`ChargePoint.call()` raises a `asyncio.TimeoutError` if a call isn't
answered withing a given time.
However, the `asyncio.TimeoutError` is missing context. The lack of
context makes interpreting this exception hard than it should be.
This commit add that context.
Fixes #200
> Add context to TimeoutErrors

- ocpp/v16/call_result.py
In ocpp 1.6, the field status is of type
DataTransferStatus, as we have it defined,
this is what we should be using for the
status field of DataTransferPayload.
> fix: use DataTransferStatus in status

- ocpp/messages.py
- tests/test_messages.py
The `message.action` is a string and it should
be compared to a string, in this case we are
interested in the `GetCompositeSchedule` action.
This closes #217
> fix: parser for float in GetComposite action

- ocpp/v16/schemas/MeterValues.json
**Context:**
From OCPP 1.6, section 7.33:
>MeterValue
>Class
>Collection of one or more sampled values in MeterValues.req. All sampled values in a MeterValue are
>sampled at the same point in time.
>sampledValue
>Required. One or more measured values
**Problem**:
The v16/schemas/MeterValues.json accepts the following:
Empty list of meterValue
```
{
"connectorId": 22883461,
"meterValue": [],
"transactionId": -15150072
}
```
Empty list of sampledValue
```
{
"connectorId": 22883461,
"meterValue": [{
"timestamp": "2020-08-19T05:35:53.953Z",
"sampledValue": []
},],
"transactionId": -15150072
}
```
**Proposal**:
I suggest to limit the length of the arrays by the use of the
minItems to 1 in both sampledValue and meterValue. Check documentation …
> fix: limit array in meterValue and sampledValue

- ocpp/messages.py
- tests/test_messages.py
When running tests I noticed the following warning: `UserWarning: Depricated as of 0.8.1. Please use `ocpp.messages.get_validator()`
As the next revision will be 0.8.4, I figured I would submit a PR to remove this warning.
> Remove depreciated get_schema code

- .circleci/config.yml
- CHANGELOG.md
- poetry.lock
`poetry` introduced some [breaking changes] in the format of the lock
file[0]. This project didn't pin the version of `poetry`, therefore the
build started to fail.
This has been fixed by pinning `poetry` and updating the lock file.
Fixes: #252
[breaking changes]: python-poetry/poetry#4523
> Fix CI build 

- pyproject.toml
> fixed authors emails as poetry publish requires the authors section to be in the format 'Name <email>'

- ocpp/charge_point.py
- tests/test_charge_point.py
`remove_nones()` only works with `list`s and `dict`s, not with other
iterables like `str`. However, the function didn't properly checked its
input and would crash when passed a `list` of `str`s.
Fixes: #289
> Fix bug in `remove_nones()` when processing `str`

- ocpp/charge_point.py
- ocpp/messages.py
- tests/test_messages.py
- tests/v16/test_v16_charge_point.py
- tests/v20/test_v20_charge_point.py
- tests/v201/test_v201_charge_point.py
Added error differentiation when schema is invalid. supporting:
- <Error in schema> : <Error sent to CP>
- Type mismatch: TypeConstraintViolationError
- Lack of properties: ProtocolError
- Non-requested properties: FormatViolationError
Now catches exceptions thrown by schema validation errors instead of
dropping the WS connection.
Previous behavior was to drop the socket connection whenever a request payload was not compliant with the schema, this PR introduces support for schema error handling according to the OCPP specification (from 1.6 to 2.0.1).
> Improved error handling during schema validation

- ocpp/messages.py
- tests/test_messages.py
According to ocpp-j-1.6-specification , section "4.2.3 CallError", a unique identifier that is too long is a reason for a call error of type TypeConstraintViolationError
> Raise maxLength violation as ocpp error

- ocpp/charge_point.py
- ocpp/exceptions.py
- ocpp/messages.py
- tests/test_messages.py
- tests/v16/test_v16_charge_point.py
- tests/v20/test_v20_charge_point.py
- tests/v201/test_v201_charge_point.py
This PR is to improve the exception handling in validating messages and to make the CallError messages closer to the OCPP spec. Quick overview:
- Added missing `NotSupported` to the exception list.
- Changed usage of `NotImplemented` to `NotSupported` when a handler doesn't exist.
- Use the default description and moved additional information to `details`
- Reduce the usage of `ValidationError` as it is not a valid OCPP error type, doesn't generate a CallError, and crashes the code when handling messages. I've tried to replace them with relevant OCPP error types.
> Improve Exception handling and CallError responses

- .github/workflows/pull-request.yml
Pinning to `3.10.0` was probably done to avoid using `3.10`, which is a YAML float with vlaue `3.1`. Instead of doing that, use a string specifier, which installs the latest bugfix release of Python 3.10 (currently 3.10.7). This will stop any possible encounters with already-fixed bugs in Python.
> Make CI use latest bugfix release of Python 3.10

- ocpp/v201/datatypes.py
This field is `retrieveDateTime` both in the spec and the json schema in this repo
> fix: incorrect name for FirmwareType field

- ocpp/messages.py
- tests/test_exceptions.py
Scope: In case an OCPP validation fails TypeConstraint or Format, we should log which message caused the validation to fail.
We noticed a reproducible TypeConstraintViolation as a reaction to an OCPP message from Etrel Chargers.
A (OCPP) response from the Etrel chargers leads to a a) problem in data type conversion/parsing, b) a debug message that a transmitted string may be too long.
> [DVI-509] OCPP Validation logging

- ocpp/__init__.py
- ocpp/charge_point.py
- ocpp/messages.py
- ocpp/routing.py
- ocpp/v16/__init__.py
- ocpp/v20/__init__.py
- ocpp/v201/__init__.py
- tests/test_exceptions.py
- tests/test_messages.py
- tests/test_routing.py
This PR adds support for OCPP spec extensions. This is the first PR adding support for V2X extensions but also enabling support for potential future extensions from the OCA. The V2X extension types, schemas, examples, and unit tests would come in a future PR.
> feat: Support OCPP spec extensions - Part 1

- .github/workflows/publish-to-pypi.yml
The unit tests aren't ran before release.
This commit fixes this to avoid releasing without
running the tests.
Fixes: https://github.com/mobilityhouse/ocpp/issues/337
> Run tests before deploying

- .github/workflows/publish-to-pypi.yml
[The publish-to-pypi build failed for 0.16.0.](https://github.com/mobilityhouse/ocpp/actions/runs/3838953465/jobs/6536318630). It seems that the issue is caused by the lack of quotes around value for field 'python-version'.
> Fix publish-to-pypi build

- ocpp/v201/datatypes.py
This PR fixes the `childCertificateHashData` field in the `CertificateHashDataChainType` as specified in OCPP 2.0.1.
> fix: child_certificate_hash_data type

- ocpp/charge_point.py
- tests/v16/conftest.py
- tests/v16/test_v16_charge_point.py
- tests/v20/conftest.py
- tests/v20/test_v20_charge_point.py
- tests/v201/conftest.py
- tests/v201/test_v201_charge_point.py
This PR adds:
-An additional optional parameter to the `call` method. 
This is needed for requirement E-13 on OCPP2.0.1 when the CS needs to retry sending a transaction message with the same ID.
Currently, when the `call` method is called, a `Call` object is created with a new random ID.
> feat: add optional param for passing an unique_id to call method.

- .github/actions/setup-python-build-env/action.yml
Currently, the build requires `poetry` 1.1.11.
That version of `poetry` is already 2 years old.
While working on #452, this old version caused trouble. As part of #452, I've to add new development dependency.
As result, `poetry.lock` is regenerated. Unfortunately, the build fails because the lock file is incompatible with `poetry` 1.1.11. See https://github.com/mobilityhouse/ocpp/actions/runs/5611599332/jobs/10268147947?pr=451
Fixes #455
> Update poetry in CI to 1.5.1

- ocpp/messages.py
This library relied on a private API of jsonschema to map a validation error to the right `OCPPError`. As of jsonschema==4.19.0, the private API has changed.[^1]. Using the latest release of jsonschema with this library caused an `ImportError`.
This commit removes the dependency on the private API.
Fixes #471 
[^1]: https://github.com/python-jsonschema/jsonschema/commit/931323043b4409a0416f373403bfb52408fc282f
> Fix "ImportError" for jsonschema

- ocpp/charge_point.py
- ocpp/messages.py
@Jared-Newell-Mobility new PR from the master branch, for background see #426
> Minor fixes

- CHANGELOG.md
- ocpp/exceptions.py
In OCPP 1.6, two errors were misspelled. "FormationViolation" Error should be "FormatViolation" Error, "OccurenceConstraintViolation" Error should be "OccurrenceConstraintViolation" Error.
The OCA decided not to correct the spelling in OCPP 1.6, since that would be a breaking change. FormationViolation has been fixed as of OCPP 2.0.1. OccurenceConstraintViolation Error is used for 1.6 and 2.0.1. "OccurrenceConstraintViolation" Error is used for OCPP 2.1 and up.
This library doesn't support "FormationViolation" Error (for OCPP 1.6 and up)
This commit  adds support for those errors.
See the discussion at https://github.com/mobilityhouse/ocpp/issues/381 and OCPP 1.6-J Errata sheet v1.0, section 5 "Known issues that won't be fixed".
> Add `FormationError` and `OccurrenceConstraintViolationError`

- ocpp/v201/datatypes.py
The V2.0.1 datatype `EventDataType` is missing an optional string attribute for techInfo.
> fix: add missing tech_info attribute to v2.0.1 EventDataType

- ocpp/charge_point.py
- ocpp/exceptions.py
- tests/v16/conftest.py
- tests/v16/test_v16_charge_point.py
- tests/v20/test_v20_charge_point.py
- tests/v201/test_v201_charge_point.py
See #426 for background discussion
> Add NotImplemented exception

- CHANGELOG.md
- ocpp/v16/enums.py
- ocpp/v201/enums.py
> V2.0.1 unit of measure update docstring to allow use for variable characteristics

- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
#531 Feat: Add 1.6 security extension datatypes. Thanks [@proelke](https://github.com/proelke)
[#528](https://github.com/mobilityhouse/ocpp/issues/528) v2.0.1 CertificateHashDataChainType childCertificateHashData requires the default of None.
[#510](https://github.com/mobilityhouse/ocpp/issues/510) v2.0.1 UnitOfMeasureType - Enums missing and update docstring to allow use for variableCharacteristics.
[#508](https://github.com/mobilityhouse/ocpp/issues/508) Exception - OccurrenceConstraintViolationError doc string correction.
> bump to 0.23.0

- CHANGELOG.md
- ocpp/v201/call.py
- ocpp/v201/call_result.py
In 2.0.1 both DataTransferRequest and DataTransferResponse have a field called `data` which is defined as `AnyType` so I believe these should both by of type `Any` here
> fix: DataTransfer data types

- CHANGELOG.md
- ocpp/charge_point.py
- To log OCPP call results to `ocpp_index`, we are currently relying on a decorator that decorates the `_on_action` handlers.
- At the level of those handlers we do not have access to the `message.unique_id` which  is a logging requirement, for that we decided to use `ChargePoint._handle_call` method.
- By doing so we lost access to the `response` which is also a required field for the logging.
- To resolve this, we want to make `ChargePoint._handle_call` has the `response` as return value. 
[CHAR-3326]: https://mobilityhouse.atlassian.net/browse/CHAR-3326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ChargePoint._handle_call return response

- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
#539 feat: Add ChargePoint._handle_call return value. Thanks [@wafa-yah](https://github.com/wafa-yah)
#266 fix: Central System documentation link.
#516 OCPP 2.0.1 add additional security events from v1.3.
#537 Fix DataTransfer data types. Thanks [@mdwcrft](https://github.com/mdwcrft)
> Bump to 0.24.0

- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
#554 OCPP 2.0.1 Edition 2 Errata 2023-12 document added
#548 OCPP 2.0.1 MessageInfoType attribute name correction
#300 OCPP 2.0.1 add reference components and variables
#518 OCPP 2.0.1 add additional reason codes from v1.3
> Bump to 0.25.0

- CHANGELOG.md
- ocpp/v16/call.py
- ocpp/v16/call_result.py
- ocpp/v201/call.py
- ocpp/v201/call_result.py
> OCPP v1.6/v2.0.1 deprecate dataclasses from calls and call results with the suffix 'Payload'

- .github/workflows/pull-request.yml
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/v16/conftest.py
- tests/v201/conftest.py
See issue https://github.com/mobilityhouse/ocpp/issues/565
> drop support for python 3.7

- .github/workflows/pull-request.yml
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/v16/conftest.py
- tests/v201/conftest.py
Reverts mobilityhouse/ocpp#585
As this is breaking should be included in release 1.0.0
> Revert "drop support for python 3.7"

- CHANGELOG.md
- ocpp/charge_point.py
- tests/test_charge_point.py
see issue https://github.com/mobilityhouse/ocpp/issues/601
> Fix case conversion for `soc` in non "State of Charge" context

- CHANGELOG.md
- ocpp/experimental/v21/README.rst
- tests/experimental/v21/README.rst
see issue https://github.com/mobilityhouse/ocpp/issues/573
> Introduce Experimental Module For v2.1

- CHANGELOG.md
- ocpp/v201/enums.py
I found a typo. Consider accepting it if it's possible
> fix typo in DataTypeEnum -> value_too_high

- ocpp/v201/enums.py
This PR intends to fix a typo in the enum for v201
> fix typo CostUpdated enum for 201

- ocpp/charge_point.py
- tests/test_charge_point.py
Serialization of a payload that contains a collection of items fails. Only the last item of the collection appears in the
serialized output. All other collections are not available.
Fixes #635
> Fix serialization of payloads that contain collection of multiple elements

- ocpp/charge_point.py
- tests/v16/conftest.py
- tests/v16/test_v16_charge_point.py
Implements schema validation skipping when running `call`.
`skip_schema_validation` is defaulted to `False`, and once set to `True`, will skip schema validation of both request and response.
Implements https://github.com/mobilityhouse/ocpp/issues/315.
> Skip schema validation on call

- ocpp/v201/call_result.py
> bugfix: Changed total_cost type from Optional[int] to Optional[float]

- ocpp/charge_point.py
Updated PR for https://github.com/mobilityhouse/ocpp/pull/641
> feat: Added optional logger param to ChargePoint class

- ocpp/charge_point.py
> add executor to validate_payload

- README.rst
From the readme in the ocpp 2.0.1 edition 3 zipfile https://openchargealliance.org/my-oca/ocpp/:
For historical reasons not all documents have the same release date. OCPP 2.0.1 Edition 3 is the same as OCPP 2.0.1 Edition 2 including all errata up and until OCPP-2.0.1_edition2_errata_2024-04 (2024-04-30).
The errata do not affect any schemas of OCPP messages. The errata do contain changes to requirements or even new requirements,
but only in cases where a requirement contains an obvious error and would not or could not be implemented literally. New
requirements were only added when they were already implicitly there.
No code changes needed to library then => Updated readme to mention edition 3 support.
> Update readme - ocpp 2 edition 3 is supported

- ocpp/charge_point.py
- ocpp/messages.py
- tests/test_exceptions.py
- tests/test_messages.py
See discussion at https://github.com/mobilityhouse/ocpp/pull/676
> Disable threads if messages.ASYNC_VALIDATION = False

- .github/workflows/inactive-issue.yml
- Issues that are stale for 30 days will be marked as `stale`
- Issues that are marked as `stale` for more than 14 days will be automatically closed.
- No changes will be done to PRs
Ref: https://docs.github.com/en/actions/use-cases-and-examples/project-management/closing-inactive-issues
> chore: Added inactive issue workflow

- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
- SUPPORT.md
Based on examples from other open-source repos in github:
- code of conduct for those participating in the project
- instructions for contributing to the project (including a pull request template to help facilitate)
- how to report a security vulnerability
- expectations of getting help with the project
Contributes to https://github.com/mobilityhouse/ocpp/issues/671
> chore: Add code of conduct, contributing, security and support docs.

- tests/v16/test_v16_charging_profiles.py
To help with PR #648 , adding a unit test to demonstrate that when creating a `RemoteStartTransaction` call, the optional `charging_profile` attribute can be set with a dictionary or directly with the CharingProfile nested dataclass.
> test: Unit test for RemoteStartTransaction nested dataclass

- ocpp/v16/call.py
- ocpp/v16/call_result.py
- ocpp/v16/datatypes.py
Updated imports for `call.py`, `call_result.py` and `datatypes.py` for `ocpp/v16` module.
Previously the imports included individual classes which are not consistent with the changes done in `ocpp/v201` module.
No changes in existing behavior. Now the imports are being done on a module level instead of individual classes.
N/A
1. [x] Does your submission pass the existing tests?
2. [ ] Are there new tests that cover these additions/changes? 
3. [x] Have you linted your code locally before submission?
> chore: Updated imports for v16 datatypes, call and call_result files

- examples/v16/central_system.py
- examples/v16/charge_point.py
- examples/v201/central_system.py
- examples/v201/charge_point.py
Updates to the example usage of the library (doc update).
#708 and #709 describe how the current examples in the documentation fail due to 1) they still use the "Payload" suffix on payload data classes, this is not part of the latest version of this library 2) breaking changes from the WebSockets library, primarily regarding the path parameter passed to the connection handler and where to find the request headers.
This PR updates the example code both for v16 and v201, so that the payload dataclass is correct and is compatible with the latest websockets library.
Only changes to documentation. However the documentation currently wouldn't support older versions of websockets library.
1. [x] Does your submission pass the existing tests?
2. [ ] Are there new tests that cover these …
> Updating examples
